# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 418277e0198b784af00f60363172bb4ef06e48b960802af6451d794cf4455b0a5e20332150535f8c9ff608ab92b9bcee309815dd19b1cd9f4e7bb1a17622fe0f

test:
  secret_key_base: 2ee9262fdf49a1d8a7c3cef4fff83f8df3f28ffccc2739fb2c2f3a8b8481fb0b3821b90b92f4d8568c0082e9849bfdeb27f5024a5bc24d9b6632098981d36354

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
